### ISSUE TITLE
register

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/PermutationGroups.jl#10]
@JuliaRegistrator register

**Comment by tweisser** [comment]
Seems that you need to call register again to confirm that you really want to start with version 0.1.1 (0.1.2 by now).

**Comment by kalmarek** [comment]
no, I think we need to wait for manual merge (but nothing has been manually merged since 2-3 weeks); I pinged someone from JuliaRegister today, let's see what happens

**Comment by tweisser** [comment]
> Also, note the warning: This looks like a new registration that registers version 0.1.1.
> Ideally, you should register an initial release with 0.0.1, 0.1.0 or 1.0.0 version numbers
> This can be safely ignored. However, if you want to fix this you can do so. Call register() again after making the fix. This will update the Pull request.

The way I interpret this, is that it is just asking for do a second call to register to confirm that you actually meant to register a version other than 1.0.0, 0.1.0, or 0.0.1.

**Comment by blegat** [comment]
You should call it again only if you changed something, I would recommend asking in `pkg-registration` on slack for help

**Comment by kalmarek** [comment]
@blegat thanks!
