### ISSUE TITLE
Character tables

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/PermutationGroups.jl#4]
Since the groups we will be working with are rather small, I think the simplest implementation is the best one.

Some links:
https://www.sciencedirect.com/science/article/pii/S0747717108800776
https://www.taylorfrancis.com/books/9780429147944
(chapter 7 gives a few pages overview)

The other option is that we fall back on GAP.jl. Possible pros/cons:
  * GAP has everything we need 
  * Julia integration is rather brand new/unstable/slow
  * we'd have to write conversions for character tables, floats, etc.
  * no binary builder at the moment
@tweisser, what do you think?

**Comment by tweisser** [comment]
I would prefer not to rely on GAP and keep the implementation as as small as possible. Having a look at the algorithms...

**Comment by kalmarek** [comment]
this is what I thought; we could have a look at this together (I don't know the algorithms that well), but the original Burnside shouldn't be that complicated
